Rails Group Project: Recipe app
Rachelwebdev/recipe-app pull request #22
Opened 2023-05-25 19:25 UTC by uchexm

## In this pull request, our team @Rachelwebdev and @uchexm made the following implementations 🧧

- [ ] Created and set up a Rails app with Postgres `database`.
- [ ] We built the Login and registration page with `Devise`.
- [ ] Created models based on the `ERD` diagram: `User,` `Food,` `Recipe,` and `RecipeFood`
- [ ] Created a `homepage` and `navigation` menu for the app
- [ ] A food list that displays a list of food added by the `logged-in` `user` which leads to a form to add a new food.
- [ ] A recipes list that displays recipes created by the `user` and leads to the recipe details, also the `user` can delete the recipes they created.
- [ ] A Public recipe list that displays a list of all public recipes and leads to recipe details.
- [ ] A shopping list that displays the list of food that is missing for all recipes of `the` logged-in use. 
## Technical setup

- [ ] Set up the repository on GitHub and used `Gitflow`.
- [ ] Set up Devise for `authentication`;
- [ ] Set up `RSpec` and `Capybara` testing libraries.
- [ ] **Thanks for reviewing our project. We'd love to hear your feedback and suggestions👏!**

2023-05-25 21:35 UTC, fobadara requested changes
Hi team, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Good first attempt
✅ Devise test packages are well set up
✅ Clean code

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 21:35 UTC, fobadara commented on config/routes.rb
> +  resources :public_recipes
[REQUIRED] Kindly restrict your public_recipes endpoint to only index since you have only index in your PublicRecipes controller

2023-05-25 21:35 UTC, fobadara commented on app/controllers/pages_controller.rb
> +end
[REQUIRED] Kindly remove this controller since it is not serving any purpose

2023-05-26 08:38 UTC, Rachelwebdev commented on app/controllers/users/confirmations_controller.rb
@fobadara Thank you for the review and the changes that you have requested. 👍👍

However, in implementing this particular change, my partner and I have tried the confirmation again and we are not getting this error as you did here. The account was confirmed successfully.

2023-05-26 09:39 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @uchexm and @fobadara, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You did well to fix all the requirements the previous reviewer requested.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 09:42 UTC, merged